version: "3.9"

services:
  db:
    image: postgres:15
    container_name: rlat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rlat
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init_scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db_data:
