# Generated by Django 5.1.2 on 2025-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BTCFDUSDData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(unique=True)),
                ("price", models.FloatField(null=True)),
                ("rsi_5", models.FloatField(null=True)),
                ("rsi_7", models.FloatField(null=True)),
                ("rsi_12", models.FloatField(null=True)),
                ("ema_short", models.FloatField(null=True)),
                ("ema_mid", models.FloatField(null=True)),
                ("ema_long", models.FloatField(null=True)),
                ("ema_xlong", models.FloatField(null=True)),
                ("macd_line", models.FloatField(null=True)),
                ("macd_hist", models.FloatField(null=True)),
                ("macd_signal", models.FloatField(null=True)),
                ("bb_upper", models.FloatField(null=True)),
                ("bb_middle", models.FloatField(null=True)),
                ("bb_lower", models.FloatField(null=True)),
            ],
            options={
                "db_table": '"public"."btcfdusd_data"',
            },
        ),
    ]
