# Generated by Django 5.1.2 on 2025-08-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="base_amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tick_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.tickdata"
            ),
        ),
    ]
