# Generated by Django 5.1.2 on 2025-08-20 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_btcfdusddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="trader_run_id",
                    ),
                ),
                (
                    "com_or_us",
                    models.CharField(
                        choices=[("com", "com"), ("us", "us")], max_length=3
                    ),
                ),
                ("is_testnet", models.BooleanField()),
                ("base_asset", models.CharField(max_length=7)),
                ("quote_asset", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": '"public"."trader_run"',
            },
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="bb_lower",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="bb_middle",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="bb_upper",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="ema_long",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="ema_mid",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="ema_short",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="ema_xlong",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="macd_hist",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="macd_line",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="macd_signal",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="rsi_12",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="rsi_5",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="btcfdusdtick",
            name="rsi_7",
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name="SingleBuyCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="trader_run_id",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "run_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.traderrun"
                    ),
                ),
            ],
            options={
                "db_table": '"public"."single_buy_cyle"',
            },
        ),
        migrations.CreateModel(
            name="RunTickData",
            fields=[
                ("timestamp", models.DateTimeField(unique=True)),
                ("price", models.FloatField(null=True)),
                ("rsi_5", models.FloatField(null=True)),
                ("rsi_7", models.FloatField(null=True)),
                ("rsi_12", models.FloatField(null=True)),
                ("ema_short", models.FloatField(null=True)),
                ("ema_mid", models.FloatField(null=True)),
                ("ema_long", models.FloatField(null=True)),
                ("ema_xlong", models.FloatField(null=True)),
                ("macd_line", models.FloatField(null=True)),
                ("macd_hist", models.FloatField(null=True)),
                ("macd_signal", models.FloatField(null=True)),
                ("bb_upper", models.FloatField(null=True)),
                ("bb_middle", models.FloatField(null=True)),
                ("bb_lower", models.FloatField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="trader_run_id",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("buy_prob", models.FloatField()),
                ("hold_prob", models.FloatField()),
                ("sell_prob", models.FloatField()),
                (
                    "run_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.traderrun"
                    ),
                ),
            ],
            options={
                "db_table": '"public"."run_tick_data"',
            },
        ),
    ]
