# Generated by Django 5.1.2 on 2025-08-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_runconfiguration_mlmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradingsession",
            name="blocking",
        ),
        migrations.RemoveField(
            model_name="tradingsession",
            name="data_run",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="blocking",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="data_run",
        ),
        migrations.AddField(
            model_name="runconfiguration",
            name="blocking",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tradingsession",
            name="data_runs",
            field=models.ManyToManyField(to="core.datarun"),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="data_runs",
            field=models.ManyToManyField(to="core.datarun"),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="num_episodes",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
