# Generated by Django 5.1.2 on 2025-08-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_tradingsession_blocking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradingsession",
            name="data_runs",
        ),
        migrations.AddField(
            model_name="tradingsession",
            name="data_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.datarun",
            ),
        ),
    ]
