# Generated by Django 5.1.2 on 2025-08-29 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_tradingsession_data_runs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datarun",
            name="is_futures",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tradingsession",
            name="run_configuration",
            field=models.ForeignKey(
                default="9966a6fa-632b-4cbf-8af0-a7045c4584ee",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.runconfiguration",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="run_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.runconfiguration",
            ),
        ),
    ]
