# Generated by Django 5.1.2 on 2025-09-02 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_datarun_is_futures_alter_mlmodel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickdata",
            name="direction_flag",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tickdata",
            name="long_stop_line",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tickdata",
            name="short_stop_line",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tickdata",
            name="supertrend_line",
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name="SuperTrend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("length", models.IntegerField()),
                ("multiplier", models.IntegerField()),
                ("is_sequence", models.BooleanField()),
                (
                    "base_observation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strends",
                        to="core.baseobservationset",
                    ),
                ),
            ],
            options={
                "db_table": '"public"."supertrends"',
            },
        ),
    ]
