# Generated by Django 5.1.2 on 2025-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_tickdata_direction_flag_tickdata_long_stop_line_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="supertrend",
            name="multiplier",
            field=models.FloatField(),
        ),
    ]
