# Generated by Django 5.1.2 on 2025-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS duckdb_transfers;",
            reverse_sql="DROP SCHEMA IF EXISTS duckdb_transfers CASCADE;",
        ),
        migrations.CreateModel(
            name="BTCFDUSDTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(unique=True)),
                ("price", models.FloatField()),
                ("rsi_5", models.FloatField()),
                ("rsi_7", models.FloatField()),
                ("rsi_12", models.FloatField()),
                ("ema_short", models.FloatField()),
                ("ema_mid", models.FloatField()),
                ("ema_long", models.FloatField()),
                ("ema_xlong", models.FloatField()),
                ("macd_line", models.FloatField()),
                ("macd_hist", models.FloatField()),
                ("macd_signal", models.FloatField()),
                ("bb_upper", models.FloatField()),
                ("bb_middle", models.FloatField()),
                ("bb_lower", models.FloatField()),
            ],
            options={
                "db_table": '"duckdb_transfers"."btcfdusd_ticks"',
            },
        ),
    ]
